#!/usr/bin/env bash
npx @bookshop/generate

if [[ $TRANSLATE != "true" ]];
then
  echo "🌹🌹  Generating base.json from built site with Rosey"
  npx rosey generate --source dist
  echo "🌹🌹  Generated a base.json from the built site"
  echo "🤖🤖  Generating Smartling translations"
  node rosey/utils/callSmartling.js
  echo "🤖🤖  Generated Smartling translations"
  echo "🏗️🏗️  Generating translation files from base.json"
  node rosey/utils/generateTranslationFiles.js
  echo "🏗️🏗️  Generated translation files to be edited"
  echo "🌹🌹 Syncing frontmatter with translation data files"
  node rosey/utils/syncFrontmatterTranslations.js
  node rosey/utils/syncFrontmatterUrlTranslations.js
  echo "🌹🌹 Synced new translations from frontmatter and data files"
  echo "🏗️🏗️  Generating the locales files Rosey needs from our translation files"
  node rosey/utils/generateLocales.js
  echo "🏗️🏗️  Generated locales"
fi

if [[ $TRANSLATE == "true" ]];
then
  echo "Translating site with Rosey"
  # We only want this to run on our production site, as it can interfere with CloudCannon CMS's visual editor
  # There's a little bit of shuffling around here to ensure the translated site ends up where CloudCannon picks up your site
  mv ./dist ./untranslated_site                  
  npx rosey build --source untranslated_site --dest dist
fi
